title: systemonchip
masthead_title: "System-on-Chip"
description: >-
  A blog by systemonchip.
url: "https://systemonchip.github.io"
baseurl: ""
repository: systemonchip/systemonchip.github.io
github_username: systemonchip
minimal_mistakes_skin: default
search: true
locale: en-US
timezone: Asia/Seoul

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

include:
  - _pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "systemonchip"
  avatar: "https://github.com/systemonchip.png"
  bio: "A blog by systemonchip."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/systemonchip"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/systemonchip"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
